### ISSUE TITLE
🔥

### ISSUE THREAD

**Issue by selfsigned** [wm4/wm4#1]
Thanks for your awesome work on mpv :fire: :+1: :medal_sports:

**Comment by wm4** [comment]
Let me know your favorite feature, so I can remove it.

**Comment by LaserEyess** [comment]
My favorite feature is ffmpeg support.

**Comment by richardpl** [comment]
My favorite feature is audio and video and subtitle reproduction.
Yes, just remove ffmpeg support, you are not worth using it.
