### ISSUE TITLE
Technology is our only hope

### ISSUE THREAD

**Issue by richardpl** [wm4/wm4#2]
Technology is our only hope there is no alternative.

**Comment by kierank** [comment]
Agreed, Elon will save us

**Comment by kierank** [comment]
Fixed https://github.com/kierank/wm4/blob/master/README.md

**Comment by CounterPillow** [comment]
Don't think the guy who gave known paedophiles private tours of his facilities, and most likely dabbled in child pussy himself, will save anything.

![maxwell-elon-musk-01](https://user-images.githubusercontent.com/308818/87247478-60e2e180-c454-11ea-8684-0ae4062696d0.jpg)

**Comment by wm4** [comment]
Please.
